-- Selby Premier League - Supabase starter schema
-- Run this in Supabase SQL Editor before connecting the site.

create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  sort_order int not null
);

create table if not exists public.rounds (
  id bigint generated by default as identity primary key,
  round_number int not null unique check (round_number between 1 and 9),
  play_date date null,
  host text null
);

create table if not exists public.fixtures (
  id bigint generated by default as identity primary key,
  round_number int not null references public.rounds(round_number) on delete cascade,
  player1 text not null references public.players(name),
  player2 text not null references public.players(name),
  player1_legs int null check (player1_legs between 0 and 5),
  player2_legs int null check (player2_legs between 0 and 5),
  player1_average numeric(5,2) null check (player1_average between 0 and 180),
  player2_average numeric(5,2) null check (player2_average between 0 and 180),
  unique(player1, player2),
  check (player1 <> player2)
);

create table if not exists public.league_settings (
  id int primary key default 1 check (id = 1),
  fixtures_locked boolean not null default false
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

insert into public.players(name, sort_order) values
('Bob Wilcockson',1),
('Adam England',2),
('Aaron Mills',3),
('Mark Dickinson',4),
('Craig Dickinson',5),
('Luke Kierans',6),
('Patrick Kettlewell',7),
('Josh Gibbon',8),
('Tom Littlewood',9),
('Jon Lunt',10)
on conflict (name) do nothing;

insert into public.rounds(round_number, play_date, host)
select n,
       case when n = 1 then date '2026-10-24' else null end,
       case when n = 1 then 'Bob Wilcockson' else null end
from generate_series(1,9) as n
on conflict (round_number) do nothing;

insert into public.league_settings(id, fixtures_locked)
values (1, false)
on conflict (id) do nothing;

alter table public.players enable row level security;
alter table public.rounds enable row level security;
alter table public.fixtures enable row level security;
alter table public.league_settings enable row level security;
alter table public.admin_users enable row level security;

create policy "public read players" on public.players for select using (true);
create policy "public read rounds" on public.rounds for select using (true);
create policy "public read fixtures" on public.fixtures for select using (true);
create policy "public read settings" on public.league_settings for select using (true);

create or replace function public.is_spl_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists(select 1 from public.admin_users where user_id = auth.uid());
$$;

create policy "admins manage rounds" on public.rounds
for all using (public.is_spl_admin()) with check (public.is_spl_admin());

create policy "admins manage fixtures" on public.fixtures
for all using (public.is_spl_admin()) with check (public.is_spl_admin());

create policy "admins manage settings" on public.league_settings
for all using (public.is_spl_admin()) with check (public.is_spl_admin());

-- After creating your Supabase user, add its UUID here:
-- insert into public.admin_users(user_id) values ('YOUR-AUTH-USER-UUID');
