/* Uses the site's existing Supabase client and logged-in league admin. */
(()=>{
const cache=new Map(),notices=new Map();let owner=null;
function user(){const id=state.user?.id;if(id!==owner){cache.clear();notices.clear();owner=id;}return id;}
function key(id){return 'spl-scorer-pending-v1:'+user()+':'+id;}
function pending(id){try{return JSON.parse(sessionStorage.getItem(key(id))||'null');}catch{return null;}}
function clear(id){sessionStorage.removeItem(key(id));}
function archivePending(id,p){const labels=(p.darts||[]).map(d=>d.n===0?'MISS':d.n===25?(d.m===2?'BULL':'25'):(d.m===3?'T':d.m===2?'D':'S')+d.n).join(', ');sessionStorage.setItem('spl-scorer-held-request:'+user()+':'+id+':'+p.request,JSON.stringify(p));clear(id);notices.set(id,'An older pending visit was set aside'+(labels?' ('+labels+')':'')+'. Check the saved visit history, then re-enter it only if it is missing.');}
function unpack(id,data,reset=false){const p=pending(id);if(!data){cache.delete(id);if(p?.kind==='visit')archivePending(id,p);return null;}const old=reset||data.reset_history?null:cache.get(id);const list=new Map((old?.visits||[]).map(v=>[v.revision,v]));for(const v of data.visits)list.set(v.revision,v);const match={...data,visits:[...list.values()].sort((a,b)=>a.revision-b.revision)};cache.set(id,match);
 if(p){if(p.kind==='undo'&&data.revision>p.revision)clear(id);else if(data.start_request===p.request||match.visits.some(v=>v.request_id===p.request))clear(id);else if(p.kind==='visit'&&(!p.startRequest||p.startRequest!==data.start_request||data.revision>p.revision))archivePending(id,p);}
 return match;}
async function rpc(name,args){const result=await sb.rpc(name,args);if(result.error){const error=Error(result.error.message);error.code=result.error.code;throw error;}return result.data;}
async function send(id,p){if(p.kind==='visit'&&!p.startRequest){archivePending(id,p);throw Error('This pending visit came from the older scorer. Reload the saved match and check its history before re-entering it.');}try{const data=await rpc(p.kind==='start'?'fixture_score_start':p.kind==='undo'?'fixture_score_undo':'fixture_score_submit',p.kind==='start'?{p_fixture_id:id,p_first:p.first,p_request_id:p.request}:p.kind==='undo'?{p_fixture_id:id,p_start_request:p.startRequest,p_revision:p.revision,p_request_id:p.request}:{p_fixture_id:id,p_revision:p.revision,p_request_id:p.request,p_darts:p.darts,p_start_request:p.startRequest});const result=unpack(id,data,p.kind==='start'||p.kind==='undo');clear(id);return result;}catch(e){if(e.code==='PGRST202'){clear(id);throw Error('The scorer files and database endpoint do not match. Refresh the website after installing the latest scorer database update; do not resubmit until the saved scorecard has loaded.');}if(['P0001','40001','42501','22023','22P02'].includes(e.code))clear(id);throw e;}}
window.SPLFixtureAPI={pending,notice:id=>notices.get(id)||'',
 async deleteMatch(id,snapshot,requestId){const result=await rpc('fixture_score_delete',{p_fixture_id:id,p_start_request:snapshot.start_request,p_revision:snapshot.revision,p_request_id:requestId});cache.delete(id);clear(id);for(let i=sessionStorage.length-1;i>=0;i--){const k=sessionStorage.key(i);if(k?.startsWith('spl-scorer-draft-v1:'+user()+':'+id+':')||k?.startsWith('spl-scorer-draft-v2:'+user()+':'+id+':'))sessionStorage.removeItem(k);}return result;},
 async load(id){user();return unpack(id,await rpc('fixture_score_read',{p_fixture_id:id,p_since:0}),true);},
 async start(id,first){if(pending(id))throw Error('Resolve the pending submission before starting again.');const p={kind:'start',first,revision:0,request:crypto.randomUUID()};sessionStorage.setItem(key(id),JSON.stringify(p));return send(id,p);},
 async undo(id,revision){if(pending(id))throw Error('Resolve the pending submission first.');const m=cache.get(id);if(!m?.start_request)throw Error('Reload the match first.');const p={kind:'undo',revision,startRequest:m.start_request,request:crypto.randomUUID()};sessionStorage.setItem(key(id),JSON.stringify(p));return send(id,p);},
 async submit(id,revision,darts){if(pending(id))throw Error('Resolve the pending submission before entering another visit.');const m=cache.get(id);if(!m?.start_request)throw Error('Reload the match before submitting. If its identity is still missing, apply the scorer database update.');const p={kind:'visit',revision,startRequest:m.start_request,darts:darts.map(({n,m})=>({n,m})),request:crypto.randomUUID()};sessionStorage.setItem(key(id),JSON.stringify(p));return send(id,p);},
 async retry(id){const p=pending(id);if(!p)throw Error('No pending submission. Reload the scorecard.');return send(id,p);}
};
})();
