/* League fixture scoring: immutable submitted visits, derived results. */
(()=>{'use strict';
const E=window.SPLScoring,esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let id=null,owner=null,match=null,draft=[],mode=1,selected=-1,message='',busy=false,loading=false,loadError='',ticket=0;
const root=()=>document.querySelector('#app');
const allowed=()=>!!state.user&&state.isAdmin;
const pending=()=>id&&window.SPLFixtureAPI.pending(id);
const fixture=()=>state.rounds.flatMap(r=>r.fixtures).find(f=>String(f.id)===id);
const model=()=>({...match.state,visits:match.visits.map(v=>v.visit)});
const draftKey=()=>`spl-scorer-draft-v2:${state.user?.id}:${id}:${match?.start_request}:${match?.revision}`;
function persistDraft(){try{sessionStorage.setItem(draftKey(),JSON.stringify(draft));}catch{}}
async function refresh(){const request=++ticket,requested=id;loading=true;loadError='';render();try{const data=await window.SPLFixtureAPI.load(requested);if(request!==ticket)return;match=data;draft=[];if(match){try{draft=JSON.parse(sessionStorage.getItem(draftKey())||'[]');if(draft.length)E.visit(model(),draft,match.config,true);}catch{draft=[];}}mode=1;selected=-1;message=pending()?'A submission is unresolved. Retry it before scoring more darts.':window.SPLFixtureAPI.notice?.(id)||'';syncFixture();}catch(e){if(request===ticket)loadError=e.message;}finally{if(request===ticket){loading=false;render();}}}
function syncFixture(){const f=fixture();if(!f||!match)return;const s=match.state;f.status=s.status;if(s.status==='completed'){f.s1=s.legs[0];f.s2=s.legs[1];f.pts1=s.metrics[0].points;f.pts2=s.metrics[1].points;f.darts1=s.metrics[0].darts;f.darts2=s.metrics[1].darts;f.a1=f.darts1?f.pts1*3/f.darts1:null;f.a2=f.darts2?f.pts2*3/f.darts2:null;}else{for(const k of ['s1','s2','pts1','pts2','darts1','darts2','a1','a2'])f[k]=null;}}
async function save(kind,first){if(busy||!allowed())return;const requested=id,request=ticket;busy=true;render();try{const oldKey=draftKey();const data=await (kind==='start'?window.SPLFixtureAPI.start(id,first):kind==='retry'?window.SPLFixtureAPI.retry(id):kind==='undo'?window.SPLFixtureAPI.undo(id,match.revision):window.SPLFixtureAPI.submit(id,match.revision,draft));if(request!==ticket||id!==requested)return;sessionStorage.removeItem(oldKey);match=data;draft=[];mode=1;selected=-1;message=kind==='undo'?'Last submitted visit undone. Scores and standings recalculated.':'Saved to the league database';syncFixture();}catch(e){if(request===ticket)message=e.message+(pending()?' Retry or reload to confirm whether it was saved.':'');}finally{busy=false;if(request===ticket)render();}}
function bindRecovery(){document.querySelector('#retrySave')?.addEventListener('click',()=>save('retry'));document.querySelector('#reloadMatch')?.addEventListener('click',()=>{if(!busy)refresh();});}
function add(n,m){if(busy||pending())return;try{const s=model(),prefix=selected>=0?draft.slice(0,selected):draft,p=prefix.length?E.visit(s,prefix,match.config,true):s;if(selected<0&&(prefix.length>=3||p.visits.at(-1)?.checkout&&prefix.length||p.visits.at(-1)?.bust&&prefix.length))return;const left=p.remaining[s.turn],eligible=left===50||left<=40&&left>=2&&left%2===0;const d={n,m,attempt:eligible,attemptSource:eligible?(n*m===left&&m===2?'checkout':'inferred'):'none'};const next=[...prefix,d];E.visit(s,next,match.config,true);draft=next;selected=-1;mode=1;persistDraft();render();}catch(e){message=e.message;render();}}
function avatar(name){const initials=name.trim().split(/\s+/).map(part=>part[0]).slice(0,2).join('');const player=state.players.find(p=>p.name===name);let url='';try{if(player?.avatar_url){const parsed=new URL(player.avatar_url,location.href);if(['https:','http:'].includes(parsed.protocol))url=parsed.href;}}catch{}return `<span class="sc-avatar" aria-hidden="true"><span>${esc(initials)}</span>${url?`<img src="${esc(url)}" alt="" referrerpolicy="no-referrer">`:''}</span>`;}
function metrics(s,i){const m=s.metrics[i],estimated=s.visits.some(v=>v.player===i&&v.darts.some(d=>d.attemptSource==='inferred'));return `${m.darts} darts · avg ${m.darts?(m.points*3/m.darts).toFixed(1):'—'} · ${estimated?'est. checkout':'checkout'} ${m.attempts?(100*m.checkouts/m.attempts).toFixed(0)+'%':'—'} (${m.checkouts}/${m.attempts})`;}
function render(){
 document.body.classList.add('fixture-scoring');
 if(state.loading||loading){root().innerHTML='<section class="scorer"><p>Loading scorecard…</p></section>';return;}
 if(!allowed()){root().innerHTML='<section class="scorer"><h1>Fixture scoring</h1><p>Sign in with a league admin account to score fixtures.</p><a class="btn" href="#account">Account</a><a class="btn secondary" href="#fixtures">Fixtures</a></section>';return;}
 if(loadError){root().innerHTML='<section class="scorer"><h1>Scoring unavailable</h1><p id="scoreError"></p><button id="retryLoad">Retry loading</button><a class="btn secondary" href="#fixtures">Fixtures</a></section>';document.querySelector('#scoreError').textContent=loadError;document.querySelector('#retryLoad').onclick=refresh;return;}
 const f=fixture();
 if(!match){root().innerHTML=`<section class="scorer"><div class="sc-top"><a href="#fixtures">← Fixtures</a><span>League match</span></div><h1>Start fixture scoring</h1>${!f?'<p>Fixture not found. Return to Fixtures and choose a match.</p>':`<form id="startMatch" class="sc-form"><p><strong>${esc(f.p1)}</strong> vs <strong>${esc(f.p2)}</strong></p><p>501 · double out · first to 5 legs.<br>The bull winner starts leg 1; starters alternate afterwards.</p><label>Who was closest to the bull?<select name="first" required ${busy||pending()?'disabled':''}><option value="">Choose the starting player</option><option value="0">${esc(f.p1)}</option><option value="1">${esc(f.p2)}</option></select></label><button class="sc-submit" ${busy||pending()?'disabled':''}>${busy?'Saving…':'Start match'}</button></form>`}<p class="sc-message" role="status">${esc(message)}</p>${pending()?'<button id="retrySave">Retry pending submission</button><button id="reloadMatch">Reload saved match</button>':''}<p class="sc-muted">Check each dart before submitting. Undo can roll back submitted visits.</p></section>`;document.querySelector('#startMatch')?.addEventListener('submit',e=>{e.preventDefault();save('start',Number(new FormData(e.target).get('first')));});bindRecovery();return;}
let s,base,p;try{s=model();base=s;p=draft.length?E.visit(base,draft,match.config,true):base;}catch(e){root().innerHTML=`<section class="scorer"><h1>Scoring paused</h1><p>${esc(e.message)}</p><button onclick="location.reload()">Reload saved match</button></section>`;return;}
const v=draft.length?p.visits.at(-1):null,terminal=v&&(v.bust||v.checkout),left=v?v.remaining:base.remaining[base.turn],route=E.checkout(left,3-draft.length);const entryLeft=selected>=0?(selected?E.visit(base,draft.slice(0,selected),match.config,true).remaining[base.turn]:base.remaining[base.turn]):left,eligible=entryLeft===50||entryLeft>=2&&entryLeft<=40&&entryLeft%2===0;
root().innerHTML=`<section class="scorer"><div class="sc-top"><a href="#fixtures">← Fixtures</a><span>Leg ${base.leg} · first to 5</span></div><div class="sc-pair">${match.config.players.map((name,i)=>`<article class="sc-player ${base.turn===i&&base.status==='active'?'active':''}"><div class="sc-player-heading">${avatar(name)}<div class="sc-name">${esc(name)} ${base.turn===i&&base.status==='active'?'◀':''}</div></div><div class="sc-remaining">${i===base.turn&&v?v.remaining:base.remaining[i]}</div><div class="sc-meta">${base.legs[i]} legs · ${metrics(base,i)}</div></article>`).join('')}</div>
${s.status==='completed'?`<div class="sc-finish"><span>Match complete</span><br><strong>${s.legs.join(' – ')}</strong><p>${esc(match.config.players[s.legs[0]===5?0:1])} wins</p><p><a class="btn" href="#table">View league table</a></p></div>`:`<div class="sc-hint" aria-live="polite">${v?.bust?'BUST · restores '+v.start+' · submit to confirm':v?.checkout?'GAME SHOT · submit to confirm':route?'<span class="sc-checkout-label">Checkout · '+(3-draft.length)+' dart'+(3-draft.length===1?'':'s')+' left</span><strong class="sc-checkout-route">'+route.join(' → ')+'</strong>':draft.length===3?'Visit entered · submit to continue':left>170?'Score down to a finish':'No checkout in '+(3-draft.length)+' dart'+(3-draft.length===1?'':'s')}</div><div class="sc-draft">${[0,1,2].map(i=>`<button data-slot="${i}" class="${selected===i?'selected':''}" aria-label="Edit dart ${i+1}" ${!draft[i]?'disabled':''}>${draft[i]?E.dart(draft[i]).label:'—'}${draft[i]?.attempt?' •':''}</button>`).join('')}</div><div class="sc-entry"><button id="backDart" ${!draft.length?'disabled':''}>⌫ Last dart</button><button id="submitVisit" class="sc-submit" ${!(draft.length===3||terminal)?'disabled':''}>Submit ${v?.bust?'bust':v?.checkout?'checkout':v?.points??0}</button></div><div class="sc-modes">${[2,3].map(m=>`<button data-mode="${m}" aria-pressed="${mode===m}" class="${mode===m?'selected':''}">${['Single','Double','Treble'][m-1]}</button>`).join('')}</div><div class="sc-pad">${Array.from({length:20},(_,i)=>`<button data-n="${i+1}" ${((draft.length===3||terminal)&&selected<0)?'disabled':''}>${i+1}</button>`).join('')}</div><div class="sc-extras"><button data-n="25" data-m="1">Outer 25</button><button data-n="25" data-m="2">Bull 50</button><button data-n="0" data-m="1">MISS</button></div>`}
<p class="sc-message" role="status">${esc(message)}</p><div class="sc-tools"><button id="undoVisit" ${!match.visits.length||busy||pending()?'disabled':''}>Undo last visit</button><button id="reloadMatch">Reload saved match</button>${pending()?'<button id="retrySave">Retry pending submission</button>':''}</div>
<p class="sc-muted">Undo removes the latest submitted visit and clears draft darts. Press again to go back further, including previous legs.</p>
<details><summary>Visit history · ${s.visits.length} visits</summary><div class="sc-history"><table><thead><tr><th>Leg / player</th><th>Darts</th><th>Score → left</th></tr></thead><tbody>${s.visits.slice().reverse().map(v=>`<tr><td>${v.leg} · ${esc(match.config.players[v.player])}</td><td>${v.darts.map(d=>d.label+(d.attempt?' •':'')).join(' / ')}</td><td>${v.bust?'BUST':v.points} → ${v.remaining}${v.checkout?' ✓':''}</td></tr>`).join('')}</tbody></table></div><p class="sc-muted">• Checkout attempt, automatically inferred when a finishing double is available (even 2–40 or bull 50). Average = credited points × 3 ÷ recorded darts. Bust visits credit zero. Estimated checkout % = successful checkouts ÷ counted attempts; intended aim cannot be proven from the score. These statistics reflect recorded darts only.</p></details>
<details><summary>Recorded visit audit</summary><div class="sc-history">${match.visits.slice().reverse().map(v=>`<p class="sc-muted">Visit ${v.revision} · ${esc(v.recorded_at)}<br>${esc(state.players.find(p=>p.user_id===v.actor)?.name||'League admin')}</p>`).join('')}</div><button id="exportMatch">Export scorecard</button></details><p class="sc-muted">Saved to the league database · revision ${match.revision}.</p></section>`;
root().querySelectorAll('.sc-avatar img').forEach(img=>{img.onerror=()=>img.remove();if(img.complete&&!img.naturalWidth)img.remove();});
root().querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=mode===+b.dataset.mode?1:+b.dataset.mode;render();});root().querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>add(+b.dataset.n,+(b.dataset.m||mode)));root().querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{selected=+b.dataset.slot;message='Choose the replacement dart. Later draft darts will be cleared.';render();});
const on=(sel,fn)=>root().querySelector(sel)?.addEventListener('click',fn);
on('#backDart',()=>{if(busy||pending())return;draft.pop();selected=-1;persistDraft();render();});
on('#submitVisit',()=>save('visit'));
on('#undoVisit',()=>save('undo'));
on('#exportMatch',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(match,null,2)],{type:'application/json'}));a.download='SPL-scorecard-'+id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
bindRecovery();if(busy||pending())root().querySelectorAll('[data-mode],[data-n],[data-slot],#backDart,#submitVisit').forEach(b=>b.disabled=true);
}
window.SPLFixture={escape:esc,canScore:allowed,close(){if(id!==null){ticket++;id=null;match=null;draft=[];}document.body.classList.remove('fixture-scoring');},async open(fixtureId){const nextOwner=state.user?.id;if(nextOwner!==owner){owner=nextOwner;id=null;match=null;draft=[];}if(state.loading){render();return;}if(!allowed()){id=null;render();return;}if(id!==fixtureId){id=fixtureId;await refresh();}else render();}};
if(location.hash.startsWith('#score/'))route();

// Whole-match deletion is separate from editing individual submitted visits.
document.addEventListener('click',async event=>{
 const button=event.target.closest('[data-delete-fixture]');if(!button||!allowed())return;
 const fixtureId=button.dataset.deleteFixture,dialog=document.createElement('dialog');dialog.className='fixture-delete-dialog';
 dialog.innerHTML='<h2>Delete match scores?</h2><p class="delete-description">Loading the saved match…</p><p>This permanently removes all recorded darts, visits and legs for this match and recalculates the league table. The scheduled fixture stays available to play again.</p><p class="delete-error" role="status"></p><div class="delete-actions"><button class="btn secondary" data-cancel>Cancel</button><button class="btn danger" data-confirm disabled>Delete scores</button></div>';
 document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.showModal();
 let snapshot;const requestId=crypto.randomUUID(),confirm=dialog.querySelector('[data-confirm]');
 try{snapshot=await window.SPLFixtureAPI.load(fixtureId);if(!snapshot)throw Error('No saved scores remain for this fixture. Refresh Fixtures.');dialog.querySelector('.delete-description').textContent=snapshot.config.players.join(' vs ')+' · '+snapshot.state.legs.join('–');confirm.disabled=false;}catch(e){dialog.querySelector('.delete-error').textContent=e.message;}
 confirm.onclick=async()=>{confirm.disabled=true;try{await window.SPLFixtureAPI.deleteMatch(fixtureId,snapshot,requestId);dialog.close();window.SPLFixture.close();await loadData();}catch(e){dialog.querySelector('.delete-error').textContent=e.message+' If the connection failed, retry this deletion or refresh Fixtures to check the result.';confirm.disabled=false;}};
});
})();
