/* Production profile API: existing authenticated admin RPC and public on-demand media. */
(()=>{const db=()=>window.SPL_SPRINT_CLIENT,bucket=()=>db().storage.from('spl-player-media');const unwrap=r=>{if(r.error)throw Error(r.error.message);return r.data;};const publicUrl=path=>bucket().getPublicUrl(path).data.publicUrl;
window.SPLProfileAPI={players:()=>state.players,async audio(name){const p=state.players.find(p=>p.name===name);if(!p?.walk_on_audio_path)throw Error('No walk-on audio uploaded.');return publicUrl(p.walk_on_audio_path);},async save(name,patch,avatar,audio,remove){if(!state.isAdmin)throw Error('Admin access required.');const p=state.players.find(p=>p.name===name);if(!p)throw Error('Player not found.');let avatarPath=p.profile_avatar_path||null,avatarUrl=p.avatar_url||null,audioPath=p.walk_on_audio_path||null;
 if(avatar){if(avatar.size>262144)throw Error('Photo must compress below 256 KB.');avatarPath=p.id+'/'+crypto.randomUUID()+'.webp';unwrap(await bucket().upload(avatarPath,avatar,{contentType:'image/webp',cacheControl:'86400',upsert:false}));avatarUrl=publicUrl(avatarPath);}
 if(audio){if(audio.size>5242880)throw Error('MP3 must be at most 5 MB.');audioPath=p.id+'/'+crypto.randomUUID()+'.mp3';unwrap(await bucket().upload(audioPath,audio,{contentType:'audio/mpeg',cacheControl:'86400',upsert:false}));}if(remove)audioPath=null;
 const saved=unwrap(await db().rpc('admin_update_player_profile',{p_player_id:p.id,p_expected_revision:p.profile_revision||0,p_nickname:patch.nickname,p_bio:patch.bio,p_walk_on_song:patch.walk_on_song,p_avatar_path:avatarPath,p_avatar_url:avatarUrl,p_audio_path:audioPath}));state.players=state.players.map(row=>row.id===p.id?saved:row);
 const old=[p.profile_avatar_path!==avatarPath?p.profile_avatar_path:null,p.walk_on_audio_path!==audioPath?p.walk_on_audio_path:null].filter(Boolean);if(old.length){try{unwrap(await bucket().remove(old));}catch{/* Safely handled by explicit unused-upload cleanup later. */}}
 },async cleanup(){if(!state.isAdmin)throw Error('Admin access required.');const paths=unwrap(await db().rpc('player_media_unused'));for(let i=0;i<paths.length;i+=100)unwrap(await bucket().remove(paths.slice(i,i+100).map(r=>r.path)));return paths.length;}};
})();
