(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const href=n=>'#player/'+encodeURIComponent(n),find=n=>state.players.find(p=>p.name===n);let audio=null,audioUrl=null,routeTicket=0;const inflight=new Map();
function avatar(p){return `<span class="hub-avatar">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="" loading="lazy">`:esc(initials(p.name))}</span>`;}
function person(n,photo=false){const p=find(n);return p?`<a class="hub-person" href="${href(n)}">${photo?avatar(p):''}<span>${esc(n)}</span></a>`:esc(n);}
function walkon(p){return `<section class="hub-walkon"><span class="kicker">Walk-on</span><p><strong>${esc(p.walk_on_song||'No song title added')}</strong></p>${p.walk_on_audio_path?`<button class="btn secondary" data-walkon="${esc(p.name)}">▶ Play walk-on</button><div class="hub-audio-slot"></div>`:'<span class="small">No walk-on audio uploaded yet.</span>'}</section>`;}
function stopAudio(){if(audio)audio.pause();audio=null;if(audioUrl?.startsWith('blob:'))URL.revokeObjectURL(audioUrl);audioUrl=null;}
const originalHome=renderHome;renderHome=function(){const t=document.createElement('template');t.innerHTML=originalHome();const tiles=document.createElement('section');tiles.className='hub-tiles';tiles.setAttribute('aria-label','The ten players');tiles.innerHTML=state.players.map(p=>`<a class="hub-tile" href="${href(p.name)}">${avatar(p)}<span>${esc(p.name)}</span></a>`).join('');t.content.querySelector('.hero')?.after(tiles);return t.innerHTML;};
renderPlayerProfile=function(name){const p=find(name);if(!p)return '<p>Player not found.</p>';return `<section class="card"><div class="hub-profile-heading">${avatar(p)}<div><span class="kicker">Player profile & statistics</span><h1>${esc(p.name)}</h1>${p.nickname?`<p>${esc(p.nickname)}</p>`:''}</div></div><p class="hub-bio">${esc(p.bio||'No bio added yet.')}</p><div class="profile-actions"><a class="btn secondary" href="#players">All players</a>${state.isAdmin?`<a class="btn" href="#edit-player/${encodeURIComponent(name)}">Edit profile</a>`:state.user?.id===p.user_id?'<a class="btn" href="#profile">Edit my profile</a>':''}</div>${walkon(p)}</section><section id="hubStats" class="hub-profile-statistics"><p class="hub-stats-loading">Loading player statistics…</p></section>`;};
function editor(name){if(!state.isAdmin)return '<section class="card"><h1>Admin access only</h1><p>Only the league admin can edit other players or upload walk-on audio.</p><a href="#players">Players</a></section>';const p=find(name);if(!p)return '<p>Player not found.</p>';return `<section class="hub-edit"><a href="${href(name)}">← Player profile</a><h1>Edit ${esc(name)}</h1><form id="hubEditForm" data-player="${esc(name)}"><fieldset><label>Nickname<input name="nickname" maxlength="40" value="${esc(p.nickname)}"></label><label>Bio<textarea name="bio" maxlength="300" rows="5">${esc(p.bio)}</textarea></label><label>Walk-on song title<input name="walk_on_song" maxlength="120" value="${esc(p.walk_on_song)}" placeholder="Artist – Track"></label><label>Player photo<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp"></label><label>Walk-on MP3<input name="audio" type="file" accept="audio/mpeg,.mp3"><span class="small">Maximum 5 MB. Use a short, compressed walk-on clip to keep downloads small.</span></label>${p.walk_on_audio_path?'<label><span><input name="removeAudio" type="checkbox"> Remove existing walk-on audio</span></label>':''}<button class="btn" type="submit">Save profile</button><button class="btn secondary" type="button" data-media-cleanup>Clean unused uploads</button><a class="btn secondary" href="${href(name)}">Cancel</a></fieldset><p id="hubEditMessage" role="status"></p></form></section>`;}
const oldRoute=route;route=function(){const ticket=++routeTicket;let [kind,...rest]=location.hash.slice(1).split('/'),name;try{name=decodeURIComponent(rest.join('/'));}catch{name='';}if(state.loading||state.error){oldRoute();return;}
 if(kind==='edit-player'){window.SPLFixture?.close();document.getElementById('app').innerHTML=editor(name);return;}
 if(kind==='stats'){history.replaceState(null,'',href(name));kind='player';}
 if(kind==='player'){window.SPLFixture?.close();document.getElementById('app').innerHTML=renderPlayerProfile(name);if(!find(name))return;
 if(!inflight.has(name))inflight.set(name,window.SPL_STATS.load('stats',name).finally(()=>inflight.delete(name)));
 inflight.get(name).then(()=>{if(ticket!==routeTicket)return;const target=document.getElementById('hubStats');if(!target)return;const t=document.createElement('template');t.innerHTML=window.SPL_STATS.player(name);t.content.querySelector('.st-heading')?.remove();target.replaceChildren(t.content);}).catch(()=>{if(ticket===routeTicket){const t=document.getElementById('hubStats');if(t)t.innerHTML='<p>Statistics unavailable. <button class="btn" data-hub-retry>Retry</button></p>';}});return;}
 oldRoute();};window.addEventListener('hashchange',()=>{stopAudio();route();});
async function compress(file){if(file.size>5*1024*1024)throw Error('Photo must be under 5 MB.');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.8));}finally{bitmap.close();}}
async function validAudio(file){if(!/\.mp3$/i.test(file.name))throw Error('Choose an MP3 file.');if(file.size>5*1024*1024)throw Error('Walk-on MP3 must be no larger than 5 MB.');const url=URL.createObjectURL(file);try{await new Promise((resolve,reject)=>{const a=document.createElement('audio');a.preload='metadata';const timer=setTimeout(()=>reject(Error('Could not read this MP3.')),8000);a.onloadedmetadata=()=>{clearTimeout(timer);a.removeAttribute('src');a.load();resolve();};a.onerror=()=>{clearTimeout(timer);reject(Error('This MP3 could not be read.'));};a.src=url;});}finally{URL.revokeObjectURL(url);}}
document.addEventListener('submit',async e=>{if(e.target.id!=='hubEditForm')return;e.preventDefault();if(!state.isAdmin)return;const form=e.target,msg=form.querySelector('#hubEditMessage'),fieldset=form.querySelector('fieldset');const data=new FormData(form),name=form.dataset.player;fieldset.disabled=true;msg.textContent='Saving…';try{const file=data.get('audio'),photo=data.get('avatar');if(file?.size)await validAudio(file);await window.SPLProfileAPI.save(name,{nickname:String(data.get('nickname')).trim(),bio:String(data.get('bio')).trim(),walk_on_song:String(data.get('walk_on_song')).trim()},photo?.size?await compress(photo):null,file?.size?file:null,data.get('removeAudio')==='on');state.players=window.SPLProfileAPI.players();location.hash=href(name);}catch(error){msg.textContent=error.message;msg.className='hub-error';}finally{fieldset.disabled=false;}});
document.addEventListener('click',async e=>{if(e.target.closest('[data-media-cleanup]')){const msg=document.getElementById('hubEditMessage');try{msg.textContent='Cleaning…';const n=await window.SPLProfileAPI.cleanup();msg.textContent=n+' unused uploads removed.';}catch(error){msg.textContent=error.message;}return;}if(e.target.closest('[data-hub-retry]'))route();const button=e.target.closest('[data-walkon]');if(!button)return;button.disabled=true;const section=button.closest('.hub-walkon'),slot=section.querySelector('.hub-audio-slot');try{stopAudio();const blob=await window.SPLProfileAPI.audio(button.dataset.walkon);if(!blob)throw Error('Audio unavailable.');if(!button.isConnected)return;audioUrl=blob;audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.src=audioUrl;slot.replaceChildren(audio);await audio.play().catch(()=>{});}catch(error){slot.textContent=error.message;}finally{button.disabled=false;}});
// Link roster references in rendered content without changing forms, existing links or scoring inputs.
let queued=false;function enhance(container){if(audio&&!audio.isConnected)stopAudio();const app=container||document.getElementById('app');if(!app||!state.players.length)return;
 app.querySelectorAll('a.st-history').forEach(link=>{const box=document.createElement('div');box.className=link.className;const url=link.getAttribute('href');box.innerHTML=link.innerHTML;const detail=document.createElement('a');detail.href=url;detail.textContent='Match summary →';box.append(detail);link.replaceWith(box);});
 const walker=document.createTreeWalker(app,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 const names=state.players.map(p=>p.name).sort((a,b)=>b.length-a.length);
 for(const node of nodes){if(!node.parentElement||node.parentElement.closest('a,button,select,textarea,input,script,style,svg,.hub-profile-heading,.hub-edit'))continue;let text=node.textContent;if(!names.some(n=>text.includes(n)))continue;const fragment=document.createDocumentFragment();while(text){let best=null,pos=text.length;for(const n of names){const i=text.indexOf(n);if(i>=0&&i<pos){best=n;pos=i;}}if(!best){fragment.append(text);break;}fragment.append(text.slice(0,pos));const a=document.createElement('a');a.className='hub-person';a.href=container?'../'+href(best):href(best);if(container)a.target='_top';a.textContent=best;fragment.append(a);text=text.slice(pos+best.length);}node.replaceWith(fragment);}
 app.querySelectorAll('.fixture .left .hub-person,.fixture .right .hub-person').forEach(a=>{if(a.querySelector('.hub-avatar'))return;const p=find(a.textContent);if(p)a.insertAdjacentHTML('afterbegin',avatar(p));});
 app.querySelectorAll('iframe').forEach(frame=>{if(frame.dataset.hubLinked)return;frame.dataset.hubLinked='true';const setup=()=>{try{const doc=frame.contentDocument;if(!doc?.body)return;const update=()=>enhance(doc.body);new MutationObserver(update).observe(doc.body,{childList:true,subtree:true});update();}catch{}};frame.addEventListener('load',setup);setup();});
 const start=app.querySelector('#startMatch');if(start&&!app.querySelector('.hub-bull-walkons')){const id=decodeURIComponent(location.hash.split('/')[1]||''),f=state.rounds.flatMap(r=>r.fixtures).find(f=>String(f.id)===id);if(f){const box=document.createElement('div');box.className='hub-bull-walkons';box.innerHTML=[f.p1,f.p2].map(n=>`<div>${person(n,true)}${walkon(find(n))}</div>`).join('');start.before(box);}}
}
new MutationObserver(()=>{if(!queued){queued=true;queueMicrotask(()=>{queued=false;enhance();});}}).observe(document.getElementById('app'),{childList:true,subtree:true});
document.addEventListener('play',e=>{if(e.target instanceof HTMLAudioElement){document.querySelectorAll('audio').forEach(a=>{if(a!==e.target)a.pause();});}},true);
route();enhance();
})();
